---
# tasks file for production
- name: Ensure tomcat package is present
  apt:
    name: tomcat9
    state: installed

- name: Ensure that artifact copied to prod server
  copy: src=*.war dest={{ dest_folder }}/
  notify:
  - restart tomcat