---
# tasks file for production
- name: Ensure tomcat package is present
  apt:
    name: tomcat9
    state: installed

- name: Ensure that artifact copied to prod server
  copy: src=hello-1.0.war dest={{ dest_folder }}/hello-1.0.war
  notify:
  - restart tomcat