---
- name: Ensure shared variable is defined
  hosts: all
  vars:
    artifact_name: hello-1.0.war

    
- name: Build server configuration
  hosts: build
  become: yes

  roles:
  - build

- name: Production sever configuration.
  hosts: prod
  become: yes

  roles:
  - production