---
- name: Build server configuration
  hosts: build
  become: yes

  vars:
    artifact_name: hello-1.0.war

  roles:
  - build

- name: Production sever configuration.
  hosts: prod
  become: yes

  vars:
    artifact_name: hello-1.0.war
    
  roles:
  - production
